### ISSUE TITLE
isMiddleNameValid broken

### ISSUE THREAD

**Issue by dhillman-handy** [checkr/checkr-js#4]
Relatively urgent, but we believe that the isMiddleNameValid function is not correct. It should be something like this:

``` js
isMiddleNameValid: function(middleName, noMiddleName) {
  if (noMiddleName) {
    return this.isMiddleNameEmpty(middleName) === true
  } else {
    return this.isMiddleNameEmpty(middleName) === false
  }   
}
```

with a payload including an undefined value for `middle_name` and a `true` value for `no_middle_name` we are getting "invalid middle name" errors in production. Please respond as soon as possible

**Comment by jperichon** [comment]
@dhillman-handy Thanks for submitting this issue. We are looking into this and will post a solution ASAP.

**Comment by dhillman-handy** [comment]
@jperichon thank you so much. Hope this helps.

**Comment by jperichon** [comment]
@dhillman-handy Fixed in https://github.com/checkr/checkr-js/pull/5. We made a new release, so please update the version on the URL. Thanks again for reporting this!

**Comment by dhillman-handy** [comment]
@jperichon Appreciate the quick response! We will keep you posted if we come across any additional issues. :+1:
